"use strict";
require('core-js/es6');
require('core-js/es6');
require('core-js/es7/reflect');
require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
require('@angular/platform-browser-dynamic');
require('@angular/common');
require('@angular/core');
require('@angular/router');
require('@angular/http');
require('rxjs');
